import ru from './locales/ru.json'
import kk from './locales/kk.json'
import { formatDate } from './format'

export type Locale = 'en' | 'ru' | 'kk'
export const localeNames = { en: 'English', ru: 'Русский', kk: 'Қазақша' } as const
export const intlLocales = { en: 'en-GB', ru: 'ru-RU', kk: 'kk-KZ' } as const
const dictionaries: Record<'ru' | 'kk', Record<string, string>> = { ru, kk }
const normalize = (value: string) => value.replace(/\s+/g, ' ').trim()
const escape = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const patterns = Object.keys(ru)
  .filter((key) => /\{\d+\}/.test(key))
  .map((key) => ({
    key,
    expression: new RegExp(
      '^' +
        key
          .split(/\{\d+\}/)
          .map(escape)
          .join('(.+?)') +
        '$',
    ),
  }))
  .sort((a, b) => b.key.length - a.key.length)
const cache = new Map<string, string>()

export function translate(value: string, locale: Locale, depth = 0): string {
  if (locale === 'en' || !value.trim() || depth > 5) return value
  const source = normalize(value)
  const cacheKey = `${locale}:${source}`
  let result = cache.get(cacheKey)
  if (result === undefined) {
    result = dictionaries[locale][source]
    if (result === undefined && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(source)) {
      const timestamp = new Date(source)
      result = `${formatDate(timestamp, locale, { day: '2-digit', month: 'short', year: 'numeric' })} · ${source.slice(11, 16)}`
    }
    if (result === undefined) {
      for (const pattern of patterns) {
        const match = source.match(pattern.expression)
        if (!match) continue
        result = dictionaries[locale][pattern.key].replace(/\{(\d+)\}/g, (_, index: string) =>
          translate(match[Number(index) + 1], locale, depth + 1),
        )
        break
      }
    }
    if (result === undefined && /^[-+]?\d+\.\d+%?$/.test(source)) result = source.replace('.', ',')
    if (result === undefined) {
      // Date labels generated by data services remain canonical English until display.
      const months = [
        'Jan',
        'Feb',
        'Mar',
        'Apr',
        'May',
        'Jun',
        'Jul',
        'Aug',
        'Sep',
        'Sept',
        'Oct',
        'Nov',
        'Dec',
      ]
      const date = source.match(/^(\d{1,2}) ([A-Za-z]+)(?: (\d{4}))?$/)
      if (date && months.includes(date[2])) {
        const month = months.indexOf(date[2]) - (months.indexOf(date[2]) > 8 ? 1 : 0)
        result = formatDate(new Date(Date.UTC(Number(date[3] || 2026), month, Number(date[1]))), locale, {
          day: '2-digit',
          month: 'short',
          ...(date[3] ? { year: 'numeric' } : {}),
          timeZone: 'UTC',
        })
      }
    }
    result ??= source
    if (cache.size > 3000) cache.clear()
    cache.set(cacheKey, result)
  }
  return `${value.match(/^\s*/)?.[0] || ''}${result}${value.match(/\s*$/)?.[0] || ''}`
}

export function detectLocale(saved: string | null, browserLanguages: readonly string[]): Locale {
  if (saved === 'en' || saved === 'ru' || saved === 'kk') return saved
  for (const language of browserLanguages) {
    const prefix = language.split('-')[0]
    if (prefix === 'en' || prefix === 'ru' || prefix === 'kk') return prefix
  }
  return 'en'
}
